---
api_key: YOUR API KEY
host:    0.0.0.0
port:    9699
plugins:
  Ikachan:
    scheme:  http
    host:    irc.example.com
    port:    4979
    channel: pigeon
  Mail:
    from:    pigeon@example.com
    to:
      - foo@example.com
      - bar@example.com
    subject: [notification] XXX
